name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-coverage:
    name: Run tests & collect coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_USER: dev_user
          POSTGRES_PASSWORD: dev_password
          POSTGRES_DB: omni_test
        options: >-
          --health-cmd="pg_isready -U dev_user -d omni_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure environment for onnxruntime-node (CPU only)
        run: |
          echo "ONNXRUNTIME_NODE_PREBUILT=false" >> $GITHUB_ENV
          echo "ONNXRUNTIME_NODE_CPU=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Set CI environment variables
        run: |
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "REDIS_PORT=6379" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Run Prisma migrations
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Run tests with coverage
        run: npx vitest run --coverage --coverage.reporter=lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true

  lint-and-prettier:
    name: Lint & Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure environment for onnxruntime-node (CPU only)
        run: |
          echo "ONNXRUNTIME_BUILD_FROM_SOURCE=0" >> $GITHUB_ENV
          echo "ONNXRUNTIME_USE_CUDA=0" >> $GITHUB_ENV
          echo "ONNXRUNTIME_USE_COREML=0" >> $GITHUB_ENV
          echo "ONNXRUNTIME_USE_DNNL=0" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Rebuild onnxruntime-node
        run: npm rebuild onnxruntime-node --build-from-source || true

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check
