name: Lint & Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies (skip onnxruntime-node build)
        run: |
          # Pula a instalação nativa do onnxruntime-node
          export ONNXRUNTIME_NODE_INSTALL=skip
          npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format:check
